packages:
  - 'app'
  - 'packages/*'

catalog:
  vite: '^5.0.3'
catalogs:
  svelte:
    svelte: '^5.0.0-next.1'
    '@sveltejs/kit': '^2.0.0'
    svelte-check: '^4.0.0'
    '@sveltejs/vite-plugin-svelte': '^4.0.0-next.6'
    '@sveltejs/adapter-static': '^3.0.5'