[package]
name = "fig-types"
version = "0.1.0"
edition = "2021"
license.workspace = true
repository.workspace = true

[dependencies]
ts-rs = "10.0.0"
serde = { version = "1", features = ["derive", "rc"] }
